apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/z/escritorio/database-persistent-volume"
  persistentVolumeReclaimPolicy: Delete